#pragma once

void ChooseFunction();
void UnknownOperation();
void MemoryAllocationError();
void StackIsEmpty();
void StackIsNotEmpty();
void StackPopFail();
void StackPop();
void StackClearSuccess();
void StackTopFail();
void TypeSurname();
void TypeSurnameFail();
void ErrorDuringWriteToFile();
void ErrorDuringReadToFile();
void TypeSurnameYearSubject();
void SurnameType();
void TypeYear();
void ChooseSubject();
void TypeSubject();
void TypeSubjectFail();
void InformatykaChoice();
void MatematykaChoice();
void FizykaChoice();
void MechanikaChoice();
void Quit();